################################################################################
# Use this configuration if you want the service to run on HTTPS rather than   #
# plain HTTP                                                                   #
################################################################################

[global.tls]
certs = "/root/bin/private/linfo2263.pem"
key   = "/root/bin/private/linfo2263.key"

[release]
address = "::"   # use "0.0.0.0" if you are on an ipv4 server
port    = 443     # use 443 if you want https

################################################################################
# Use this configuration if you want the service to run on plain HTTP          #
################################################################################
#[release]
#address = "::"   # use "0.0.0.0" if you are on an ipv4 server
#port    = 80     # use 443 if you want https
#
################################################################################
# Use this configuration when testing the service on your local machine        #
################################################################################
[debug]
address = "127.0.0.1"
port    = 8000

