[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/SergioBenitez/Rocket"]
git = "https://github.com/SergioBenitez/Rocket"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

